// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/exchange.proto

package gtydef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exchange int32

const (
	Exchange_GIO Exchange = 0
	Exchange_DBT Exchange = 1
)

// Enum value maps for Exchange.
var (
	Exchange_name = map[int32]string{
		0: "GIO",
		1: "DBT",
	}
	Exchange_value = map[string]int32{
		"GIO": 0,
		"DBT": 1,
	}
)

func (x Exchange) Enum() *Exchange {
	p := new(Exchange)
	*p = x
	return p
}

func (x Exchange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exchange) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_exchange_proto_enumTypes[0].Descriptor()
}

func (Exchange) Type() protoreflect.EnumType {
	return &file_protos_exchange_proto_enumTypes[0]
}

func (x Exchange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exchange.Descriptor instead.
func (Exchange) EnumDescriptor() ([]byte, []int) {
	return file_protos_exchange_proto_rawDescGZIP(), []int{0}
}

var File_protos_exchange_proto protoreflect.FileDescriptor

var file_protos_exchange_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x74, 0x79, 0x2a, 0x1c, 0x0a, 0x08,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x49, 0x4f, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x42, 0x54, 0x10, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x6d,
	0x61, 0x68, 0x61, 0x72, 0x61, 0x6a, 0x2f, 0x67, 0x74, 0x79, 0x64, 0x65, 0x66, 0x2f, 0x67, 0x74,
	0x79, 0x64, 0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_exchange_proto_rawDescOnce sync.Once
	file_protos_exchange_proto_rawDescData = file_protos_exchange_proto_rawDesc
)

func file_protos_exchange_proto_rawDescGZIP() []byte {
	file_protos_exchange_proto_rawDescOnce.Do(func() {
		file_protos_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_exchange_proto_rawDescData)
	})
	return file_protos_exchange_proto_rawDescData
}

var file_protos_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_exchange_proto_goTypes = []interface{}{
	(Exchange)(0), // 0: gty.Exchange
}
var file_protos_exchange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_exchange_proto_init() }
func file_protos_exchange_proto_init() {
	if File_protos_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_exchange_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_exchange_proto_goTypes,
		DependencyIndexes: file_protos_exchange_proto_depIdxs,
		EnumInfos:         file_protos_exchange_proto_enumTypes,
	}.Build()
	File_protos_exchange_proto = out.File
	file_protos_exchange_proto_rawDesc = nil
	file_protos_exchange_proto_goTypes = nil
	file_protos_exchange_proto_depIdxs = nil
}
