// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/ob.proto

package gtydef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bp  float64 `protobuf:"fixed64,1,opt,name=bp,proto3" json:"bp,omitempty"`
	Ap  float64 `protobuf:"fixed64,2,opt,name=ap,proto3" json:"ap,omitempty"`
	Bv  float64 `protobuf:"fixed64,3,opt,name=bv,proto3" json:"bv,omitempty"`
	Av  float64 `protobuf:"fixed64,4,opt,name=av,proto3" json:"av,omitempty"`
	Sym string  `protobuf:"bytes,5,opt,name=sym,proto3" json:"sym,omitempty"`
	Ex  string  `protobuf:"bytes,6,opt,name=ex,proto3" json:"ex,omitempty"`
	Ts  int64   `protobuf:"varint,7,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *L1) Reset() {
	*x = L1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_ob_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L1) ProtoMessage() {}

func (x *L1) ProtoReflect() protoreflect.Message {
	mi := &file_protos_ob_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L1.ProtoReflect.Descriptor instead.
func (*L1) Descriptor() ([]byte, []int) {
	return file_protos_ob_proto_rawDescGZIP(), []int{0}
}

func (x *L1) GetBp() float64 {
	if x != nil {
		return x.Bp
	}
	return 0
}

func (x *L1) GetAp() float64 {
	if x != nil {
		return x.Ap
	}
	return 0
}

func (x *L1) GetBv() float64 {
	if x != nil {
		return x.Bv
	}
	return 0
}

func (x *L1) GetAv() float64 {
	if x != nil {
		return x.Av
	}
	return 0
}

func (x *L1) GetSym() string {
	if x != nil {
		return x.Sym
	}
	return ""
}

func (x *L1) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *L1) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_protos_ob_proto protoreflect.FileDescriptor

var file_protos_ob_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x67, 0x74, 0x79, 0x22, 0x76, 0x0a, 0x02, 0x4c, 0x31, 0x12, 0x0e, 0x0a, 0x02,
	0x62, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x62, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x61, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x61, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x62, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x62, 0x76, 0x12, 0x0e, 0x0a, 0x02,
	0x61, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x61, 0x76, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x79, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x79, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x65, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x42, 0x28,
	0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65,
	0x76, 0x65, 0x6e, 0x6d, 0x61, 0x68, 0x61, 0x72, 0x61, 0x6a, 0x2f, 0x67, 0x74, 0x79, 0x64, 0x65,
	0x66, 0x2f, 0x67, 0x74, 0x79, 0x64, 0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ob_proto_rawDescOnce sync.Once
	file_protos_ob_proto_rawDescData = file_protos_ob_proto_rawDesc
)

func file_protos_ob_proto_rawDescGZIP() []byte {
	file_protos_ob_proto_rawDescOnce.Do(func() {
		file_protos_ob_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ob_proto_rawDescData)
	})
	return file_protos_ob_proto_rawDescData
}

var file_protos_ob_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_ob_proto_goTypes = []interface{}{
	(*L1)(nil), // 0: gty.L1
}
var file_protos_ob_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ob_proto_init() }
func file_protos_ob_proto_init() {
	if File_protos_ob_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_ob_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ob_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ob_proto_goTypes,
		DependencyIndexes: file_protos_ob_proto_depIdxs,
		MessageInfos:      file_protos_ob_proto_msgTypes,
	}.Build()
	File_protos_ob_proto = out.File
	file_protos_ob_proto_rawDesc = nil
	file_protos_ob_proto_goTypes = nil
	file_protos_ob_proto_depIdxs = nil
}
