// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/ResResp.proto

package gtydef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Ok    Status = 0
	Status_Error Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Ok",
		1: "Error",
	}
	Status_value = map[string]int32{
		"Ok":    0,
		"Error": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_ResResp_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_ResResp_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_ResResp_proto_rawDescGZIP(), []int{0}
}

var File_protos_ResResp_proto protoreflect.FileDescriptor

var file_protos_ResResp_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x52, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x74, 0x79, 0x2a, 0x1b, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x6d, 0x61, 0x68,
	0x61, 0x72, 0x61, 0x6a, 0x2f, 0x67, 0x74, 0x79, 0x64, 0x65, 0x66, 0x2f, 0x67, 0x74, 0x79, 0x64,
	0x65, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_ResResp_proto_rawDescOnce sync.Once
	file_protos_ResResp_proto_rawDescData = file_protos_ResResp_proto_rawDesc
)

func file_protos_ResResp_proto_rawDescGZIP() []byte {
	file_protos_ResResp_proto_rawDescOnce.Do(func() {
		file_protos_ResResp_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_ResResp_proto_rawDescData)
	})
	return file_protos_ResResp_proto_rawDescData
}

var file_protos_ResResp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_ResResp_proto_goTypes = []interface{}{
	(Status)(0), // 0: gty.Status
}
var file_protos_ResResp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_ResResp_proto_init() }
func file_protos_ResResp_proto_init() {
	if File_protos_ResResp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_ResResp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_ResResp_proto_goTypes,
		DependencyIndexes: file_protos_ResResp_proto_depIdxs,
		EnumInfos:         file_protos_ResResp_proto_enumTypes,
	}.Build()
	File_protos_ResResp_proto = out.File
	file_protos_ResResp_proto_rawDesc = nil
	file_protos_ResResp_proto_goTypes = nil
	file_protos_ResResp_proto_depIdxs = nil
}
